#!/bin/bash

TMP_ROOT="$(dirname "${BASH_SOURCE[@]}")/.."
REPO_ROOT=$(readlink -e "${TMP_ROOT}" 2> /dev/null)


ESPNAPI="http://fantasy.espn.com/apis/v3/games/ffl/seasons/2018/segments/0/leagues/432343?view=mBoxscore&view=mMatchupScore&view=mSchedule&view=mScoreboard&view=mSettings&view=mStatus&view=mTeam&view=mRoster&view=modular&view=mNav"

curl -s "${ESPNAPI}" | gojson -name=FFL -pkg=generated -o ${REPO_ROOT}/pkg/api/v3/generated/espnV3.go

sed -i '1i\/\/ This file is generated by running \`make generateAPI\`' ${REPO_ROOT}/pkg/api/v3/generated/espnV3.go
