#!/bin/bash

TEMP_DIR=`mktemp -d`
TMP_ROOT="$(dirname "${BASH_SOURCE[@]}")/.."
REPO_ROOT=$(readlink -e "${TMP_ROOT}" 2> /dev/null || perl -MCwd -e 'print Cwd::abs_path shift' "${TMP_ROOT}")

echo $REPO_ROOT

function clean {
    rm -rf "${TEMP_DIR}"
}

trap clean EXIT

ESPNAPI="http://fantasy.espn.com/apis/v3/games/ffl/seasons/2018/segments/0/leagues/432343?view=mBoxscore&view=mMatchupScore&view=mSchedule&view=mScoreboard&view=mSettings&view=mStatus&view=mTeam&view=mRoster&view=modular&view=mNav"

# Generate struct for everything
curl -s "${ESPNAPI}" | gojson -name=FFL -pkg=generated -o ${REPO_ROOT}/pkg/api/v3/generated/espnV3.go

# Generate smaller structs
curl -s "${ESPNAPI}" -o "${TEMP_DIR}/espn-json"
structs=$(JSON_DIR="${TEMP_DIR}/espn-json" python ${REPO_ROOT}/hack/string-to-json.py)

for struct in $structs; do
    cat "${TEMP_DIR}/${struct}" | gojson -name="${struct}" -pkg=generated -o "${REPO_ROOT}/pkg/api/v3/generated/${struct}.go"
    echo -e "// This file is generated by running \`make generateAPI\`\n$(cat ${REPO_ROOT}/pkg/api/v3/generated/${struct}.go)" > ${REPO_ROOT}/pkg/api/v3/generated/${struct}.go 
done

echo -e "// This file is generated by running \`make generateAPI\`\n$(cat ${REPO_ROOT}/pkg/api/v3/generated/espnV3.go)" > ${REPO_ROOT}/pkg/api/v3/generated/espnV3.go 
